[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
magicEnabled = false
fastReruns = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"
